{
    "name"                 :  "Website: Firebase Auth",
    "summary"              :  "Login & Signup with Google Firebase API",
    "category"             :  "Website",
    "version"              :  "1.0.0",
    "sequence"             :  1,
    "author"               :  "",
    "license"              :  "Other proprietary",
    "website"              :  " ",
    "description"          :  """ """,
    "live_test_url"        :  "",
    "depends"              :  ['website'],
    "data"                 :  ['views/website_templates.xml'],
    "images"               :  ['static/description/Banner.png'],
    "application"          :  True,
    "installable"          :  True,
    "auto_install"         :  False,
    "price"                :  0,
    "currency"             :  "EUR",
}
